# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 762e541120a1e9d56244912aa7f6a85b2f47cd4c10492f4b3fb83973b4b50aae9ed95194bbfc318e3629ad522e0abbe46b941431602d1216957820c3e0555c44

test:
  secret_key_base: 1bc42f87eaecbb0daa5a538aebbc4338a637c8b8cb910ffd7eebedf4bae5243fac79e6dcf30f9b71c2bc4a23790850fbe7a03a352efe3caff8c60864163a39be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
